version: '3'

services:
  ubuntu_container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    tty: true
    stdin_open: true
    environment:
      - UID=${UID}
      - GID=${GID}
