version: '3.8'

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        UID: ${UID}
        GID: ${GID}
    env_file:
      - .env
    restart: unless-stopped
    tty: true
